# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: https://rwguerra.github.io
baseurl: https://rwguerra.github.io
title: Ricardo Wagner C. Guerra Filho
author: Ricardo Guerra
keywords: Data Science, Ciência de Dados, Machine Learning, Engineering, Deep Learning
description: Ricardo Wagner Guerra - Engineer pursuing a Master's degree in Electrical Engineering @ UFPB.| Data Science, ML, DL enthusiast |
avatar: profile.png # picture
email: rwguerra@gmail.com # email
github: rwguerra # username
twitter: cadoguerra # username
linkedin: guerraricardo # username
medium: rwguerra # username
instagram: cadoguerra # username
google_analytics: UA-178428297-1

# needed for travis-ci build
exclude: [vendor]
